name: Build and Publish OpenFaaS Functions to GHCR

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Set lower case owner name
        run: echo "OWNER_LC=${OWNER,,}" >> $GITHUB_ENV
        env:
          OWNER: ${{ github.repository_owner }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install faas-cli
        run: curl -sLSf https://cli.openfaas.com | sudo sh

      - name: Pull OpenFaaS templates
        run: faas-cli template pull

      - name: Set up QEMU (multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build functions (OpenFaaS)
        run: faas-cli build -f stack.yaml

      - name: Push images to GHCR
        env:
          OWNER: ${{ github.repository_owner }}
        run: |
          # Modifier les images dans stack.yaml pour utiliser ghcr.io/OWNER/nom-image
          yq e '.functions |= with_entries(.value.image = "ghcr.io/${OWNER_LC}/" + .key + ":${GITHUB_SHA}")' stack.yaml > stack-ghcr.yaml
          faas-cli push -f stack-ghcr.yaml
