name: Build and Publish OpenFaaS Function

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install faas-cli
        run: curl -sLSf https://cli.openfaas.com | sudo sh

      - name: Pull OpenFaaS templates
        run: faas-cli template pull

      - name: Set up QEMU (multi-arch build)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push OpenFaaS function(s)
        run: |
          faas-cli publish --platforms linux/amd64,linux/arm/v7,linux/arm64

      # Optionnel : déployer automatiquement après le push
      # - name: Login to OpenFaaS Gateway
      #   run: echo "${{ secrets.OPENFAAS_PASSWORD }}" | faas-cli login --gateway ${{ secrets.OPENFAAS_URL }} --password-stdin

      # - name: Deploy to OpenFaaS
      #   run: faas-cli deploy --gateway ${{ secrets.OPENFAAS_URL }}
